---
title: "Predictor Data Prep: Geomorphology and Soils"
author: "[Skyler Lewis](mailto:slewis@flowwest.com)"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
    toc_depth: 3
    number_sections: false
    math_method:
      engine: webtex
      url: https://latex.codecogs.com/svg.image?
---


```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(stars)
library(tidymodels)

theme_set(theme_minimal())

source(here::here("data-raw", "scripts", "data-functions.R"))

flowlines <- readRDS(here::here("data-raw", "results", "flowline_geometries_proj.Rds"))
flowlines_gcs <- readRDS(here::here("data-raw", "results", "flowline_geometries.Rds"))

flowline_attributes <- readRDS(here::here("data-raw", "results", "flowline_attributes.Rds"))

# for context mapping
flowlines_sac_valley_major <- 
  flowlines_gcs |>
  filter(comid %in% (
    flowline_attributes |> 
      filter(gnis_name %in% 
               c("Sacramento River", 
                 "Feather River", 
                 "Pit River")) |>
      pull(comid)
  ))

```

## Soils

```{r soils-data}
soils <- 
  st_read(file.path("/vsizip", here::here("data-raw", "source", "soils", "Cal_STATSGO2.shp.zip")), as_tibble=T) |>
  st_transform(project_crs) |>
  janitor::clean_names() |> 
  transmute(soil_drainage = factor(drainage, levels=c("Very poorly drained",
                                                      "Poorly drained",
                                                      "Somewhat poorly drained",
                                                      "Well drained",
                                                      "Somewhat excessively drained",
                                                      "Excessively drained")),
            soil_hsg = factor(hydro_g, levels=c("A","B","C","D")),
            soil_salt_accum = factor(salt, levels=c("acid","nonacid","euic","calcareous")),
            soil_climate = factor(climate, levels=c("frigid","mesic","thermic","hyperthermic","isofrigid","isomesic","isothermic","isohyperthermic")),
            soil_minerology = factor(minerology, levels=c("superactive","active","semiactive","subactive")),
            soil_volcanic = if_else(str_detect(texture,"ashy") | str_detect(texture,"cindery") | str_detect(texture,"medial"), 1, 0),
            soil_texture_simple = case_when(str_detect(word(texture,1), "ashy") ~ "ashy",
                                            str_detect(word(texture,1), "medial") ~ "medial",
                                            str_detect(word(texture,1), "clayey") ~ "clayey",
                                            str_detect(word(texture,1), "clayey") ~ "silty",
                                            str_detect(word(texture,1), "clayey") ~ "sandy",
                                            str_detect(word(texture,1), "clayey") ~ "loamy",
                                            str_detect(word(texture,1), "clayey") ~ "fine"
                                            ) |> factor())

soils_comid <-
  flowlines_gcs |>
  select(comid) |>
  st_point_on_surface() |>
  st_transform(st_crs(soils)) |>
  st_join(soils) |>
  st_drop_geometry() |>
  glimpse()

soils_comid |> saveRDS(here::here("data-raw", "results", "attr_soils.Rds"))
```

## UCD Geomorphology classes (experimental)

This is a very rough generalization of spot classifications to the entire basin. Use with caution!

```{r geomorph-data-import}
geomorph_site_data <- 
  tibble(result=rjson::fromJSON(file=here::here("data-raw", "source", "ucd_geomorph", "geoSites.json"))) |> 
  unnest_wider(result) |> 
  mutate(geomorph_region = map_chr(geoClass, function(x) x$geoRegion$abbreviation),
         geomorph_class = map_chr(geoClass, function(x) x$name),
         geomorph_class_median_attributes = map(geoClass, function(x) x$medianAttributes),
         geometry = map(geometry, function(x) c(x$coordinates[[2]], x$coordinates[[1]]) |> st_point()) |> st_sfc(crs="EPSG:4326")) |>
  janitor::clean_names() |> 
  st_as_sf() |>
  filter(geomorph_region=="SAC") |>
  select(identity, geometry, geomorph_class) |>
  mutate(identity = str_replace(identity, "SAC_", ""),
         geomorph_class_num=str_replace(geomorph_class, "SAC-","") |> as.numeric(),
         geomorph_class = factor(geomorph_class, 
                                 levels = paste0("SAC-",seq(1,10,1)),
                                 labels = c("SAC-1"  = "Unconfined, boulder-bedrock, bed undulating",
                                            "SAC-2"  = "Confined, boulder, high gradient, step-pool/cascade",
                                            "SAC-3"  = "Confined, boulder-bedrock, uniform",
                                            "SAC-4"  = "Confined, boulder-bedrock, low-gradient step-pool",
                                            "SAC-5"  = "Confined, gravel-cobble, uniform",
                                            "SAC-6"  = "Partly-confined, low width-to-depth ratio, gravel-cobble, riffle-pool",
                                            "SAC-7"  = "Partly-confined, cobble-boulder, uniform",
                                            "SAC-8"  = "Partly-confined, high width-to-depth ratio, gravel-cobble, riffle-pool",
                                            "SAC-9"  = "Unconfined, low width-to-depth ratio, gravel",
                                            "SAC-10" = "Unconfined, gravel-cobble, riffle-pool"))) |>
  inner_join(read_csv(here::here("data-raw", "source", "ucd_geomorph", "geomorph_site_attributes.csv")), by=join_by(identity)) |>
  st_transform(project_crs) |> 
  st_join(flowlines |> select(comid), join=st_nearest_feature)

geomorph_site_data |> 
  ggplot() + 
  geom_sf(aes(color=geomorph_class)) + 
  geom_sf(data=flowlines_sac_valley_major, color="darkgray")

geomorph_site_data |> select(comid, starts_with("geomorph_")) |>
  saveRDS(here::here("data-raw", "results", "geomorph_sites_ucd.Rds"))

flowlines_gcs |> 
  inner_join(geomorph_site_data |> st_drop_geometry()) |> 
  ggplot() + geom_sf(aes(color=geomorph_class)) + 
  scale_fill_brewer(type="qual", palette="Paired", aesthetics = c("fill", "color"))
```

```{r}
geomorph_attr <- 
  geomorph_site_data |>
  left_join(flowline_attributes |> select(-starts_with("geomorph_")), by=join_by(comid)) |>
  mutate(geomorph_confined = str_split_i(geomorph_class, ", ", 1) |> as_factor(),
         geomorph_uniform = str_detect(geomorph_class, "uniform"),
         geomorph_steppool = str_detect(geomorph_class, "step-pool"), 
         geomorph_riffles = str_detect(geomorph_class, "riffle"),
         geomorph_gravel = str_detect(geomorph_class, "gravel"),
         geomorph_spawning = (geomorph_riffles | geomorph_steppool)) 

geomorph_attr |>
  ggplot() +
  geom_point(aes(x = slope*100, y = da_area_sq_km, color = geomorph_riffles)) + 
  scale_x_log10() + scale_y_log10() + annotation_logticks() +
  theme(panel.grid.minor = element_blank()) 

geomorph_attr |>
  ggplot() +
  geom_point(aes(x = slope*100, y = da_area_sq_km, color = geomorph_class)) + 
  scale_x_log10() + scale_y_log10() + annotation_logticks() +
  theme(panel.grid.minor = element_blank()) 

```

```{r geomorph-fill-gaps, eval=FALSE, include=FALSE}
geomorph_training_data <- 
  geomorph_site_data |>
  left_join(flowline_attributes |> select(-starts_with("geomorph_")), by=join_by(comid)) |>
  select(comid, geomorph_class, geomorph_class_num,
         da_area_sq_km, slope, bf_depth_m, bf_width_m, bf_w_d_ratio,  
         mtpi30_min, loc_k_erodibility, sinuosity, da_elev_mean, da_ppt_mean_mm, 
         ) |>
  drop_na() |>
  st_drop_geometry()

geomorph_rec <- 
  recipe(geomorph_class ~ da_area_sq_km + slope + bf_depth_m + bf_width_m + bf_w_d_ratio + 
         mtpi30_min + loc_k_erodibility + sinuosity + da_elev_mean + da_ppt_mean_mm,
         data=geomorph_training_data)

geomorph_spec <- rand_forest(mode = "classification", trees = 256)

geomorph_fit <- 
  workflow() |>
  add_recipe(geomorph_rec) |>
  add_model(geomorph_spec) |>
  fit(data=geomorph_training_data)

geomorph_prediction_data <- flowlines_gcs |>
  left_join(flowline_attributes, by=join_by(comid)) |>
  filter(substr(reachcode,1, 4) %in% c("1802", "1803", "1804", "1805")) |>
  select(comid, 
         da_area_sq_km, slope, bf_depth_m, bf_width_m, bf_w_d_ratio,  
         mtpi30_min, loc_k_erodibility, sinuosity, da_elev_mean, da_ppt_mean_mm
         ) |>
  drop_na() |>
  st_drop_geometry()
  
geomorph_pred <- 
  geomorph_prediction_data |>
  mutate(geomorph_class = predict(geomorph_fit, geomorph_prediction_data)[[".pred_class"]]) |>
  mutate(geomorph_confined = str_split_i(geomorph_class, ", ", 1) |> as_factor(),
         geomorph_uniform = str_detect(geomorph_class, "uniform"),
         geomorph_steppool = str_detect(geomorph_class, "step-pool"), 
         geomorph_riffles = str_detect(geomorph_class, "riffle"),
         geomorph_gravel = str_detect(geomorph_class, "gravel"),
         geomorph_spawning = (geomorph_riffles | geomorph_steppool))


flowlines_gcs |> 
  inner_join(geomorph_pred, by=join_by(comid)) |> 
  ggplot() + geom_sf(aes(color=geomorph_class)) + 
  scale_fill_brewer(type="qual", palette="Paired", aesthetics = c("fill", "color"))

flowlines_gcs |> 
  inner_join(geomorph_pred, by=join_by(comid)) |> 
  ggplot() + geom_sf(aes(color=geomorph_confined)) 

flowlines_gcs |> 
  inner_join(geomorph_pred, by=join_by(comid)) |> 
  ggplot() + geom_sf(aes(color=geomorph_steppool)) 

flowlines_gcs |> 
  inner_join(geomorph_pred, by=join_by(comid)) |> 
  ggplot() + geom_sf(aes(color=geomorph_riffles))

flowlines_gcs |> 
  inner_join(geomorph_pred, by=join_by(comid)) |> 
  ggplot() + geom_sf(aes(color=geomorph_gravel)) 

# # validation matrix
# geomorph_training_data |>
#   select(comid, geomorph_class_actual=geomorph_class) |>
#   inner_join(geomorph_pred |> select(comid, geomorph_class_pred=geomorph_class)) |>
#   group_by(geomorph_class_actual, geomorph_class_pred) |>
#   tally() |> 
#   mutate(n=coalesce(n,0)) |>
#   spread(geomorph_class_actual, n)

ggplot() +
  geom_point(data=geomorph_pred, aes(x = slope*100, y = da_area_sq_km, color = (geomorph_riffles | geomorph_steppool)), size=0.25) + 
  geom_point(data=geomorph_attr, aes(x = slope*100, y = da_area_sq_km, fill = (geomorph_riffles | geomorph_steppool)), shape=21, size=2) + 
  scale_x_log10() + scale_y_log10() + annotation_logticks() +
  theme(panel.grid.minor = element_blank()) 

ggplot() +
  geom_point(data=geomorph_pred, aes(x = slope*100, y = da_area_sq_km, color = geomorph_class), size=0.25) + 
  geom_point(data=geomorph_attr, aes(x = slope*100, y = da_area_sq_km, fill = geomorph_class), shape=21, size=2) + 
  scale_x_log10() + scale_y_log10() + annotation_logticks() +
  theme(panel.grid.minor = element_blank())  + 
  scale_fill_brewer(type="qual", palette="Paired", aesthetics = c("fill", "color"))

#  ggplot() +
#    geom_point(data=geomorph_pred, aes(x = slope*100, y = da_area_sq_km, color = geomorph_class), size=0.25) + 
#    geom_point(data=geomorph_attr, aes(x = slope*100, y = da_area_sq_km, fill = geomorph_class), shape=21, size=2) + 
#    scale_x_log10() + scale_y_log10() + annotation_logticks() +
#    theme(panel.grid.minor = element_blank())  + 
#    scale_fill_brewer(type="qual", palette="Paired", aesthetics = c("fill", "color")) +
#    theme(legend.position = "none")
```

```{r geomorph-export, eval=FALSE, fig.height=12, fig.width=12, dpi=300, include=FALSE}
ggplot() + 
  geom_sf(data = left_join(flowlines, geomorph_pred), aes(color = geomorph_class)) + 
  geom_sf(data = geomorph_site_data, aes(fill = geomorph_class), shape=21) + 
  scale_fill_brewer(type="qual", palette="Paired", aesthetics = c("fill", "color"))

geomorph_pred |> select(comid, starts_with("geomorph_")) |>  #select(comid, geomorph_class) |> 
  saveRDS(here::here("data-raw", "results", "attr_geomorph_class.Rds"))
```

```{r geomorph-fill-gaps-train}
geomorph_training_data <- 
  geomorph_site_data |>
  left_join(flowline_attributes |> select(-starts_with("geomorph_")), by=join_by(comid), relationship="many-to-many") |>
  select(comid, geomorph_class, geomorph_class_num,
         slope, da_area_sq_km, da_elev_min, da_elev_max, da_elev_rel, da_ppt_mean_mm, mtpi30_min, hqt_gradient_class, hyd_cls) |>
  drop_na() |>
  filter(slope>1E-5) |>
  st_drop_geometry()

pca <- princomp(scale(geomorph_training_data |> select(-comid, -starts_with("geomorph_"), -hqt_gradient_class, -hyd_cls)))
factoextra::fviz_eig(pca, choice="variance", addlabels = TRUE)
factoextra::fviz_pca_var(pca, axes=c(1,2), col.var = "cos2", repel = TRUE)
factoextra::fviz_pca_var(pca, axes=c(1,3), col.var = "cos2", repel = TRUE)
factoextra::fviz_pca_var(pca, axes=c(1,4), col.var = "cos2", repel = TRUE)

geomorph_rec <- 
  recipe(geomorph_class ~ slope + da_area_sq_km + da_elev_min + da_elev_max + da_elev_rel + da_ppt_mean_mm + mtpi30_min + hqt_gradient_class + hyd_cls,
         data=geomorph_training_data) |>
  #step_log(all_numeric_predictors()) |>#, -mtpi30_min) |>
  step_mutate_at(all_numeric_predictors(), fn = asinh) |>
  step_normalize(all_numeric_predictors()) |>
  step_pca(all_numeric_predictors(), num_comp = 4) |>
  step_dummy(hqt_gradient_class) |>
  step_dummy(hyd_cls) |>
  step_naomit()

geomorph_spec <- rand_forest(mode = "classification", trees = 256)

geomorph_fit <- 
  workflow() |>
  add_recipe(geomorph_rec) |>
  add_model(geomorph_spec) |>
  fit(data=geomorph_training_data)
```

```{r geomorph-fill-gaps-predict}
geomorph_prediction_data <- flowlines_gcs |>
  left_join(flowline_attributes, by=join_by(comid)) |>
  filter(substr(reachcode,1, 4) %in% c("1802", "1803", "1804")) |>
  select(comid, 
         slope, da_area_sq_km, da_elev_min, da_elev_max, da_elev_rel, da_ppt_mean_mm, hqt_gradient_class, hyd_cls, mtpi30_min) |>
  drop_na() |>
 # filter(da_elev_min > 0) |>
  st_drop_geometry()
  
geomorph_pred <- 
  geomorph_prediction_data |>
  mutate(geomorph_class = predict(geomorph_fit, geomorph_prediction_data)[[".pred_class"]]) |>
  mutate(geomorph_confined = str_split_i(geomorph_class, ", ", 1) |> as_factor(),
         geomorph_uniform = str_detect(geomorph_class, "uniform"),
         geomorph_steppool = str_detect(geomorph_class, "step-pool"), 
         geomorph_riffles = str_detect(geomorph_class, "riffle"),
         geomorph_gravel = str_detect(geomorph_class, "gravel"),
         geomorph_spawning = (geomorph_riffles | geomorph_steppool))
  
flowlines_gcs |> 
  inner_join(geomorph_pred, by=join_by(comid)) |> 
  ggplot() + geom_sf(aes(color=geomorph_class)) + 
  scale_fill_brewer(type="qual", palette="Paired", aesthetics = c("fill", "color"))

# validation matrix
geomorph_training_data |>
  select(comid, geomorph_class_actual=geomorph_class) |>
  inner_join(geomorph_pred |> select(comid, geomorph_class_pred=geomorph_class)) |>
  group_by(geomorph_class_actual, geomorph_class_pred) |>
  tally() |> 
  mutate(n=coalesce(n,0)) |>
  spread(geomorph_class_actual, n) |>
  knitr::kable()

ggplot() +
  geom_point(data=geomorph_pred, aes(y = slope, x = da_area_sq_km, color = geomorph_class), size=0.25) + 
  geom_point(data=geomorph_attr, aes(y = slope, x = da_area_sq_km, fill = geomorph_class), shape=21, size=2) + 
  scale_y_log10(labels  = scales::label_percent()) + scale_x_log10(labels  = scales::label_comma()) + annotation_logticks() +
  theme(panel.grid.minor = element_blank())  + 
  scale_fill_brewer(type="qual", palette="Paired", aesthetics = c("fill", "color")) +
  theme(legend.position = "none") + ylab("Slope (%)") + xlab("Drainage Area (km2)")

ggplot() +
  geom_point(data=geomorph_pred, aes(x = da_area_sq_km, y = da_elev_min/0.3048, color = geomorph_class), size=0.25) + 
  geom_point(data=geomorph_attr, aes(x = da_area_sq_km, y = da_elev_min/0.3048, fill = geomorph_class), shape=21, size=2) + 
  scale_y_sqrt(labels = scales::label_comma()) + scale_x_log10(labels  = scales::label_comma())  + annotation_logticks(sides="b") +
  theme(panel.grid.minor = element_blank())  + 
  scale_fill_brewer(type="qual", palette="Paired", aesthetics = c("fill", "color")) +
  theme(legend.position = "none") + xlab("Drainage Area (km2)") + ylab("Elevation (ft)")

```

```{r geomorph-export2, fig.width=12, fig.height=12, dpi=300}
ggplot() + 
  geom_sf(data = left_join(flowlines, geomorph_pred), aes(color = geomorph_class)) + 
  geom_sf(data = geomorph_site_data, aes(fill = geomorph_class), shape=21) + 
  scale_fill_brewer(type="qual", palette="Paired", aesthetics = c("fill", "color"))

geomorph_pred |> select(comid, starts_with("geomorph_")) |>  #select(comid, geomorph_class) |> 
  saveRDS(here::here("data-raw", "results", "attr_geomorph_class.Rds"))
```
